name: 'Data atlan integration'
description: 'update atlan data catalog'
inputs:
  atlan_api_key:
    description: 'atlan api key'
    required: true
  atlan_instance:
    description: 'atlan instance'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ATLAN_API_KEY: ${{ inputs.atlan_api_key }}
    ATLAN_INSTANCE: ${{ inputs.atlan_instance }}