name: 'Data atlan integration'
description: 'update atlan data catalog'
inputs:
  atlan_api_token:
    description: 'Atlan api key'
    required: true
  atlan_instance:
    description: 'Atlan instance'
    required: true
  atlan_athena_connection_id:
    description: 'Atlan athena connection id'
    required: true
  atlan_redshift_connection_id:
    description: 'Atlan redshift connection id'
    required: true
  atlan_team:
    description: 'Atlan team tag'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ATLAN_API_TOKEN: ${{ inputs.atlan_api_token }}
    ATLAN_INSTANCE: ${{ inputs.atlan_instance }}
    ATLAN_ATHENA_CONNECTION_ID: ${{ inputs.atlan_athena_connection_id }}
    ATLAN_REDSHIFT_CONNECTION_ID: ${{ inputs.atlan_redshift_connection_id }}
    ATLAN_TEAM: ${{ inputs.atlan_team }}