name: 'Data atlan integration'
description: 'update atlan data catalog'
inputs:
  atlan_api_key:
    description: 'atlan api key'
    required: true
  atlan_instance:
    description: 'atlan instance'
    required: true
  atlan_prod_aws_account_id:
    description: 'AWS prod account ID'
    required: true
  atlan_redshift_server_url:
    description: 'Redshift server url'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ATLAN_API_KEY: ${{ inputs.atlan_api_key }}
    ATLAN_INSTANCE: ${{ inputs.atlan_instance }}
    ATLAN_PROD_AWS_ACCOUNT_ID: ${{ inputs.atlan_prod_aws_account_id }}
    ATLAN_REDSHIFT_SERVER_URL: ${{ inputs.atlan_redshift_server_url }}