Headers:
  - Table/Entity
  - Column/Attribute
  - Type
  - Summary (Description)
  - Readme
  - Lineage Type (Source / Target)
  - Lineage Integration Type
  - Lineage Schema/Database
  - Lineage Table/Entity
  - Lineage Column/Attribute
  - Term
  - Glossary
  - Classification

DynamoDbDataTypes:
  - number
  - boolean
  - string
  - binary
  - map
  - 'null'
  - list
  - set_string
  - set_number
  - set_binary
